# Generated by Django 4.1.7 on 2023-04-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_institution_paragraph_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
