# Generated by Django 4.1.7 on 2023-04-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='paragraph_id',
        ),
        migrations.AddField(
            model_name='keyword',
            name='doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paragraph'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='part_of_speech',
            field=models.TextField(null=True),
        ),
    ]
