# Generated by Django 4.1.7 on 2023-04-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_keyword_paragraph_id_keyword_doc_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='word',
        ),
    ]
