# Generated by Django 4.1.7 on 2023-04-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_keyword_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='pronunciation',
            field=models.TextField(null=True),
        ),
    ]
