# Generated by Django 4.1.7 on 2023-04-26 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_keyword_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='paragraph_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='paragraph_id',
        ),
        migrations.RemoveField(
            model_name='name',
            name='paragraph_id',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='keyword',
            name='paragraphs',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='api.paragraph'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='keywords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
