# Generated by Django 4.1.7 on 2023-04-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0002_document_file_name'),
        ('authentication', '0004_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
